#ifndef _JINUE_KERNEL_HAL_ASM_THREAD_H_
#define _JINUE_KERNEL_HAL_ASM_THREAD_H_

#define THREAD_CONTEXT_BITS     9

#define THREAD_CONTEXT_SIZE     (1 << THREAD_CONTEXT_BITS)

#define THREAD_CONTEXT_MASK     (THREAD_CONTEXT_SIZE - 1)

#endif
