#!/bin/sh

GUARD="KERNEL_BUILD_INFO_H"
GIT_REVISION=`git rev-parse --short HEAD`
BUILD_TIME=`LANG=en date`
BUILD_HOST=`hostname -s`
SELF=`basename $0`

echo "/* This file is auto-generated by scripts/$SELF"
echo " * during the build process. */"
echo ""
echo "#ifndef $GUARD"
echo "#define $GUARD"
echo ""
echo "#define GIT_REVISION    \"$GIT_REVISION\""
echo "#define BUILD_TIME      \"$BUILD_TIME\""
echo "#define BUILD_HOST      \"$BUILD_HOST\""
echo ""
echo "#endif"
